// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTEjFmp8m_8tE97bKvnNV5X9uFFmnvNss',
    appId: '1:465618077633:web:eb846cdbd9e011120f1140',
    messagingSenderId: '465618077633',
    projectId: 'flash-chat-c283a',
    authDomain: 'flash-chat-c283a.firebaseapp.com',
    storageBucket: 'flash-chat-c283a.firebasestorage.app',
    measurementId: 'G-L1B570VMCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl6VYA6uSXx8m8mL0_o0ZmIi5gAVfMerA',
    appId: '1:465618077633:android:c05dbbb3e7651edd0f1140',
    messagingSenderId: '465618077633',
    projectId: 'flash-chat-c283a',
    storageBucket: 'flash-chat-c283a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2iKrkUYe47AchgsECoM8xBmJG9lrQHLg',
    appId: '1:465618077633:ios:6e1576b5700eca000f1140',
    messagingSenderId: '465618077633',
    projectId: 'flash-chat-c283a',
    storageBucket: 'flash-chat-c283a.firebasestorage.app',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2iKrkUYe47AchgsECoM8xBmJG9lrQHLg',
    appId: '1:465618077633:ios:6e1576b5700eca000f1140',
    messagingSenderId: '465618077633',
    projectId: 'flash-chat-c283a',
    storageBucket: 'flash-chat-c283a.firebasestorage.app',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTEjFmp8m_8tE97bKvnNV5X9uFFmnvNss',
    appId: '1:465618077633:web:c76d8c7b1a6554d80f1140',
    messagingSenderId: '465618077633',
    projectId: 'flash-chat-c283a',
    authDomain: 'flash-chat-c283a.firebaseapp.com',
    storageBucket: 'flash-chat-c283a.firebasestorage.app',
    measurementId: 'G-18FG3E71YT',
  );
}
