// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuNSskPmRVmbq030UJ3oETbwab7mpNnbg',
    appId: '1:683447097939:web:237e9def2e7ddadfeb44a6',
    messagingSenderId: '683447097939',
    projectId: 'authentication-7c7df',
    authDomain: 'authentication-7c7df.firebaseapp.com',
    storageBucket: 'authentication-7c7df.firebasestorage.app',
    measurementId: 'G-PD2P3TW5JE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZfXytLoCdEygkoHRtRdRgS6P2eC7iKiU',
    appId: '1:683447097939:android:1ab9187f25cc7753eb44a6',
    messagingSenderId: '683447097939',
    projectId: 'authentication-7c7df',
    storageBucket: 'authentication-7c7df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoV43LwPXVCnaX88leZEu8fmRiwOvXo6s',
    appId: '1:683447097939:ios:fbc65a75ca9c6b67eb44a6',
    messagingSenderId: '683447097939',
    projectId: 'authentication-7c7df',
    storageBucket: 'authentication-7c7df.firebasestorage.app',
    iosBundleId: 'com.example.loginFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoV43LwPXVCnaX88leZEu8fmRiwOvXo6s',
    appId: '1:683447097939:ios:fbc65a75ca9c6b67eb44a6',
    messagingSenderId: '683447097939',
    projectId: 'authentication-7c7df',
    storageBucket: 'authentication-7c7df.firebasestorage.app',
    iosBundleId: 'com.example.loginFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuNSskPmRVmbq030UJ3oETbwab7mpNnbg',
    appId: '1:683447097939:web:c8306898f4fbf48beb44a6',
    messagingSenderId: '683447097939',
    projectId: 'authentication-7c7df',
    authDomain: 'authentication-7c7df.firebaseapp.com',
    storageBucket: 'authentication-7c7df.firebasestorage.app',
    measurementId: 'G-82ZJ7GKX14',
  );
}
